6108

diff --git a/package/IPQ6108/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic b/package/IPQ6108/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
--- a/package/IPQ6108/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
+++ b/package/IPQ6108/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
@@ -1,185 +1,245 @@
 #!/bin/sh /etc/rc.common
+# SPDX-License-Identifier: GPL-3.0-only
+#
+# Copyright (C) 2019-2022 Tianling Shen <cnsztl@immortalwrt.org>
 
-START=96
+USE_PROCD=1
+
+START=99
 STOP=10
 
-lan_addr="$(uci get network.lan.ipaddr)"
+NAME="unblockneteasemusic"
+UPGRADE_CONF="/lib/upgrade/keep.d/$NAME"
 
-enable="$(uci get unblockneteasemusic.@unblockneteasemusic[0].enable)"
-http_port="$(uci get unblockneteasemusic.@unblockneteasemusic[0].http_port)"
-https_port="$(uci get unblockneteasemusic.@unblockneteasemusic[0].https_port)"
-music_source="$(uci get unblockneteasemusic.@unblockneteasemusic[0].music_source)"
-music_customize_source="$(uci get unblockneteasemusic.@unblockneteasemusic[0].music_customize_source)"
-hijack_ways="$(uci get unblockneteasemusic.@unblockneteasemusic[0].hijack_ways)"
-endpoint="$(uci get unblockneteasemusic.@unblockneteasemusic[0].endpoint_enable)"
-force_best_quality="$(uci get unblockneteasemusic.@unblockneteasemusic[0].force_best_quality)"
-search_limit="$(uci get unblockneteasemusic.@unblockneteasemusic[0].search_limit)"
-auto_update="$(uci get unblockneteasemusic.@unblockneteasemusic[0].auto_update)"
-extFile="/usr/share/UnblockNeteaseMusic/extFile.txt"
-serverCrt="/usr/share/UnblockNeteaseMusic/server.crt"
-serverKey="/usr/share/UnblockNeteaseMusic/server.key"
-serverCsr="/usr/share/UnblockNeteaseMusic/server.csr"
-caCrt="/usr/share/UnblockNeteaseMusic/ca.crt"
-caKey="/usr/share/UnblockNeteaseMusic/ca.key"
-logFile="/tmp/unblockneteasemusic.log"
-exArgs=" "
-set_ipset() {
-	if [ "${set_type}" = "start" ]; then
-		mkdir -p "/tmp/dnsmasq.d"
-		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
-		cat <<-EOF >"/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
-			ipset=/.music.163.com/unblockneteasemusic
-			ipset=/interface.music.163.com/unblockneteasemusic
-			ipset=/interface3.music.163.com/unblockneteasemusic
-			ipset=/apm.music.163.com/unblockneteasemusic
-			ipset=/apm3.music.163.com/unblockneteasemusic
-		EOF
-		/etc/init.d/dnsmasq reload >"/dev/null" 2>&1
-		if ! ipset list unblockneteasemusic >"/dev/null"; then ipset create unblockneteasemusic list:set; fi
+IPT_N="iptables -t nat"
 
-		if ! ipset list unblockneteasemusic4 >"/dev/null"; then ipset create unblockneteasemusic4 hash:ip family inet; fi
-		curl -s "http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" | grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' | sort | uniq | awk '{print "ipset add unblockneteasemusic4 "$1}' | bash >"/dev/null" 2>&1
-		ipset add unblockneteasemusic unblockneteasemusic4
-		iptables -t nat -N cloud_unblockneteasemusic
-		iptables -t nat -A cloud_unblockneteasemusic -d 0.0.0.0/8 -j RETURN
-		iptables -t nat -A cloud_unblockneteasemusic -d 10.0.0.0/8 -j RETURN
-		iptables -t nat -A cloud_unblockneteasemusic -d 127.0.0.0/8 -j RETURN
-		iptables -t nat -A cloud_unblockneteasemusic -d 169.254.0.0/16 -j RETURN
-		iptables -t nat -A cloud_unblockneteasemusic -d 172.16.0.0/12 -j RETURN
-		iptables -t nat -A cloud_unblockneteasemusic -d 192.168.0.0/16 -j RETURN
-		iptables -t nat -A cloud_unblockneteasemusic -d 224.0.0.0/4 -j RETURN
-		iptables -t nat -A cloud_unblockneteasemusic -d 240.0.0.0/4 -j RETURN
-		iptables -t nat -A cloud_unblockneteasemusic -p tcp --dport 80 -j REDIRECT --to-ports "${http_port}"
-		iptables -t nat -A cloud_unblockneteasemusic -p tcp --dport 443 -j REDIRECT --to-ports "${https_port}"
-		iptables -t nat -I PREROUTING -p tcp -m set --match-set unblockneteasemusic dst -j cloud_unblockneteasemusic
-		ip6tables -h
-		if [ $? -eq 0 ]; then
-			# ipv6
-			if ! ipset list unblockneteasemusic6 >"/dev/null"; then ipset create unblockneteasemusic6 hash:ip family inet6; fi
-			domains="music.163.com"
-			for domain in $domains; do
-				ip=$(nslookup music.163.com | grep "Address " | grep -v "\." | awk '{print $3}')
-				if [ -n "$ip" ]; then
-					for addr in $ip; do
-						ipset add unblockneteasemusic6 $addr
-					done
-				else
-					echo "Query bad address,please check IPv6 DNS forwards.if IPv6 DNS forwards is enabled, please restart" >>"${logFile}"
-				fi
-			done
-			ipset add unblockneteasemusic unblockneteasemusic6
-			ip6tables -t nat -N cloud_unblockneteasemusic
-			ip6tables -t nat -A cloud_unblockneteasemusic -d ::/8 -j RETURN
-			ip6tables -t nat -A cloud_unblockneteasemusic -d FE80::/10 -j RETURN
-			ip6tables -t nat -A cloud_unblockneteasemusic -d FC00::/7 -j RETURN
-			ip6tables -t nat -A cloud_unblockneteasemusic -d FEC0::/10 -j RETURN
-			ip6tables -t nat -A cloud_unblockneteasemusic -p tcp --dport 80 -j REDIRECT --to-ports "${http_port}"
-			ip6tables -t nat -A cloud_unblockneteasemusic -p tcp --dport 443 -j REDIRECT --to-ports "${https_port}"
-			ip6tables -t nat -I PREROUTING -p tcp -m set --match-set unblockneteasemusic dst -j cloud_unblockneteasemusic
-		else
-			echo "ip6tables is not supported" >>"${logFile}"
-		fi
-		mkdir -p /var/etc
-		cat <<-EOF >>"/var/etc/unblockneteasemusic.include"
-			/etc/init.d/unblockneteasemusic restart
-		EOF
-	elif [ "${set_type}" = "stop" ]; then
-		iptables -t nat -D PREROUTING -p tcp -m set --match-set unblockneteasemusic dst -j cloud_unblockneteasemusic
-		iptables -t nat -F cloud_unblockneteasemusic
-		iptables -t nat -X cloud_unblockneteasemusic
-		ipset destroy unblockneteasemusic
-		ipset destroy unblockneteasemusic4
-		ip6tables -h
-		if [ $? -eq 0 ]; then
-			ip6tables -t nat -D PREROUTING -p tcp -m set --match-set unblockneteasemusic dst -j cloud_unblockneteasemusic
-			ip6tables -t nat -F cloud_unblockneteasemusic
-			ip6tables -t nat -X cloud_unblockneteasemusic
-			ipset destroy unblockneteasemusic6
-		fi
-		echo "" >"/var/etc/unblockneteasemusic.include"
-		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
-		/etc/init.d/dnsmasq reload >"/dev/null" 2>&1
+is_enabled() {
+	local enabled
+	config_get_bool enabled "$1" "$2" "${3:-0}"
+	if [ "$enabled" -eq "1" ]; then
+		return 0
+	else
+		return 1
 	fi
 }
 
-set_hosts() {
-	if [ "${set_type}" = "start" ]; then
+append_param() {
+	procd_append_param command "$1" $2
+}
+
+append_param_arg() {
+	local value
+	config_get value "$1" "$2" $4
+	[ -n "$value" ] && append_param "$3" "$value"
+}
+
+append_param_env() {
+	local value
+	config_get value "$1" "$2" $4
+	[ -n "$value" ] && procd_append_param env "$3"="$value"
+}
+
+append_filter_client() {
+	local cfg="$1"
+
+	local ip_addr filter_mode
+	config_get ip_addr "$cfg" "ip_addr"
+	config_get filter_mode "$cfg" "filter_mode"
+	[ -n "$ip_addr" -a -n "$filter_mode" ] || return 1
+
+	case "${filter_mode}" in
+	"disable_http")
+		ipset -! add "acl_neteasemusic_http" "${ip_addr}"
+		;;
+	"disable_https")
+		ipset -! add "acl_neteasemusic_https" "${ip_addr}"
+		;;
+	"disable_all")
+		ipset -! add "acl_neteasemusic_http" "${ip_addr}"
+		ipset -! add "acl_neteasemusic_https" "${ip_addr}"
+		;;
+	esac
+}
+
+start_service() {
+	config_load "$NAME"
+	is_enabled "config" "enable" || return 1
+
+	local update_time
+	config_get update_time "config" "update_time" "3"
+	sed -i "/$NAME/d" /etc/crontabs/root
+	is_enabled "config" "auto_update" && echo "0 ${update_time} * * * /usr/share/$NAME/update.sh update_core" >> "/etc/crontabs/root"
+	echo "*/5 * * * * /usr/share/$NAME/log_check.sh" >> "/etc/crontabs/root"
+	/etc/init.d/cron restart
+
+	[ ! -s "/usr/share/$NAME/core/app.js" ] && { rm -f "/usr/share/$NAME/local_ver"; sh "/usr/share/$NAME/update.sh" "update_core_non_restart"; }
+	[ ! -s "/usr/share/$NAME/core/app.js" ] && { echo "Core Not Found, please download it before starting." >> "/tmp/$NAME.log"; exit 1; }
+
+	procd_open_instance "$NAME"
+	procd_set_param command node "/usr/share/$NAME/core/app.js"
+	append_param "-a" "0.0.0.0"
+
+	local http_port https_port hijack_ways
+	config_get http_port "config" "http_port" "5200"
+	config_get https_port "config" "https_port" "5201"
+	config_get hijack_ways "config" "hijack_ways" "use_ipset"
+	[ "${hijack_ways}" = "use_hosts" ] && { http_port="80"; https_port="443"; }
+	append_param "-p" "${http_port}":"${https_port}"
+
+	if is_enabled "config" "pub_access"; then
+		iptables -I "INPUT" -p "tcp" --dport "${http_port}" -j "ACCEPT"
+		iptables -I "INPUT" -p "tcp" --dport "${https_port}" -j "ACCEPT"
+		echo "${http_port}:${https_port}" > "/tmp/$NAME.ports"
+
+		mkdir -p "/var/etc/"
+		echo "/etc/init.d/$NAME restart" > "/var/etc/$NAME.include"
+	fi
+
+	local music_source
+	config_get music_source "config" "music_source" "default"
+	[ "${music_source}" != "default" ] && append_param -o "${music_source}"
+
+	append_param_arg "config" "cnrelay" "-c"
+	append_param_arg "config" "endpoint_url" "-e" "https://music.163.com"
+	append_param_arg "config" "netease_server_ip" "-f"
+	append_param_arg "config" "proxy_server_ip" "-u"
+	is_enabled "config" "strict_mode" && append_param "-s"
+
+	local log_level
+	config_get log_level "config" "log_level" "info"
+	procd_set_param env LOG_FILE="/tmp/$NAME.log"
+	procd_append_param env LOG_LEVEL="$log_level"
+
+	append_param_env "config" "joox_cookie" "JOOX_COOKIE"
+	append_param_env "config" "migu_cookie" "MIGU_COOKIE"
+	append_param_env "config" "qq_cookie" "QQ_COOKIE"
+	append_param_env "config" "youtube_key" "YOUTUBE_KEY"
+	append_param_env "config" "self_issue_cert_crt" "SIGN_CERT" "/usr/share/$NAME/core/server.crt"
+	append_param_env "config" "self_issue_cert_key" "SIGN_KEY" "/usr/share/$NAME/core/server.key"
+
+	is_enabled "config" "follow_source_order" && procd_append_param env FOLLOW_SOURCE_ORDER="true"
+	is_enabled "config" "enable_flac" && procd_append_param env ENABLE_FLAC="true"
+	is_enabled "config" "local_vip" && procd_append_param env ENABLE_LOCAL_VIP="true"
+	is_enabled "config" "disable_upgrade_check" && procd_append_param env DISABLE_UPGRADE_CHECK="true"
+	case "$(config_get "config" "replace_music_source")" in
+		"lower_than_192kbps") procd_append_param env MIN_BR="192000" ;;
+		"lower_than_320kbps") procd_append_param env MIN_BR="320000" ;;
+		"lower_than_999kbps") procd_append_param env MIN_BR="600000" ;;
+		"replace_all") procd_append_param env MIN_BR="9999999" ;;
+	esac
+
+	procd_set_param stdout 1
+	procd_set_param stderr 1
+	procd_set_param respawn
+
+	local lan_addr="$(uci -q get network.lan.ipaddr)"
+	if [ "${hijack_ways}" = "use_ipset" ]; then
 		mkdir -p "/tmp/dnsmasq.d"
-		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
-		cat <<-EOF >"/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
+		rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
+		cat <<-EOF > "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
+			dhcp-option=252,http://${lan_addr}:${http_port}/proxy.pac
+			ipset=/.music.163.com/neteasemusic
+			ipset=/interface.music.163.com/neteasemusic
+			ipset=/interface3.music.163.com/neteasemusic
+			ipset=/apm.music.163.com/neteasemusic
+			ipset=/apm3.music.163.com/neteasemusic
+			ipset=/clientlog.music.163.com/neteasemusic
+			ipset=/clientlog3.music.163.com/neteasemusic
+		EOF
+		/etc/init.d/dnsmasq reload
+
+		ipset create "acl_neteasemusic_http" hash:ip
+		ipset create "acl_neteasemusic_https" hash:ip
+		ipset create "neteasemusic" hash:ip
+		config_foreach append_filter_client "acl_rule"
+
+		local netease_music_ips="$(uclient-fetch -qO- "http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.data.*.ip.*')"
+		local netease_music_ips2="$(uclient-fetch -qO- "https://music.httpdns.c.163.com/d" --post-data="music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.dns.*["ips"].*')"
+		echo -e "${netease_music_ips}\n${netease_music_ips2}" | sort -u | awk '{print "ipset add neteasemusic "$1}' | sh
+
+		$IPT_N -N "netease_cloud_music"
+		for local_addr in "0.0.0.0/8" "10.0.0.0/8" "127.0.0.0/8" "169.254.0.0/16" "172.16.0.0/12" "192.168.0.0/16" "224.0.0.0/4" "240.0.0.0/4"; do
+			$IPT_N -A "netease_cloud_music" -d "${local_addr}" -j "RETURN"
+		done
+
+		$IPT_N -A "netease_cloud_music" -p "tcp" -m "set" ! --match-set "acl_neteasemusic_http" "src" --dport "80" -j "REDIRECT" --to-ports "${http_port}"
+		$IPT_N -A "netease_cloud_music" -p "tcp" -m "set" ! --match-set "acl_neteasemusic_https" "src" --dport "443" -j "REDIRECT" --to-ports "${https_port}"
+		$IPT_N -I "PREROUTING" -p "tcp" -m "set" --match-set "neteasemusic" "dst" -j "netease_cloud_music"
+
+		mkdir -p "/var/etc/"
+		echo "/etc/init.d/$NAME restart" > "/var/etc/$NAME.include"
+	elif [ "${hijack_ways}" = "use_hosts" ]; then
+		mkdir -p "/tmp/dnsmasq.d"
+		rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
+		cat <<-EOF > "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
+			dhcp-option=252,http://${lan_addr}:${http_port}/proxy.pac
 			address=/music.163.com/${lan_addr}
 			address=/interface.music.163.com/${lan_addr}
 			address=/interface3.music.163.com/${lan_addr}
 			address=/apm.music.163.com/${lan_addr}
 			address=/apm3.music.163.com/${lan_addr}
+			address=/clientlog.music.163.com/${lan_addr}
+			address=/clientlog3.music.163.com/${lan_addr}
 			address=/music.httpdns.c.163.com/0.0.0.0
 		EOF
-		/etc/init.d/dnsmasq reload >"/dev/null" 2>&1
-		# ip route add 223.252.199.10 dev lo
-	elif [ "${set_type}" = "stop" ]; then
-		rm -f "/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf"
-		/etc/init.d/dnsmasq reload >"/dev/null" 2>&1
-		# ip route del 223.252.199.10
+		/etc/init.d/dnsmasq reload
+
+		ip route add "223.252.199.10" dev lo
 	fi
+
+	procd_close_instance
+} >"/dev/null" 2>&1
+
+stop_service() {
+	config_load "$NAME"
+
+	sed -i "/$NAME/d" "/etc/crontabs/root"
+	/etc/init.d/cron restart
+
+	rm -f "${UPGRADE_CONF}"
+	is_enabled "config" "keep_core_when_upgrade" && {
+		echo "/usr/share/$NAME/core/" >> "${UPGRADE_CONF}"
+		echo "/usr/share/$NAME/local_ver" >> "${UPGRADE_CONF}"
+	}
+
+	local self_issue_cert_crt self_issue_cert_key
+	config_get "self_issue_cert_crt" "config" "self_issue_cert_crt"
+	config_get "self_issue_cert_key" "config" "self_issue_cert_key"
+	{ [ -f "${self_issue_cert_crt}" ] && [ -f "${self_issue_cert_key}" ]; } && {
+		echo "${self_issue_cert_crt}" >> "${UPGRADE_CONF}"
+		echo "${self_issue_cert_key}" >> "${UPGRADE_CONF}"
+	}
+
+	local settable
+	[ ! -e "/tmp/$NAME.ports" ] || {
+		iptables -D "INPUT" -p "tcp" --dport "$(awk -F ':' '{print $1}' "/tmp/$NAME.ports")" -j "ACCEPT"
+		iptables -D "INPUT" -p "tcp" --dport "$(awk -F ':' '{print $2}' "/tmp/$NAME.ports")" -j "ACCEPT"
+	}
+	rm -f "/tmp/$NAME.ports"
+
+	$IPT_N -D "PREROUTING" -p "tcp" -m set --match-set "neteasemusic" "dst" -j "netease_cloud_music"
+	$IPT_N -F "netease_cloud_music"
+	$IPT_N -X "netease_cloud_music"
+
+	for settable in "acl_neteasemusic_http" "acl_neteasemusic_https" "local_addr" "neteasemusic"; do
+		ipset destroy "$settable"
+	done
+
+	echo "" > "/var/etc/$NAME.include"
+
+	rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
+	/etc/init.d/dnsmasq reload
+
+	ip route del "223.252.199.10"
+
+	rm -f "/tmp/$NAME.log"
+} >"/dev/null" 2>&1
+
+reload_service() {
+	stop
+	start
 }
-createCertificate() {
-	echo "create certificate..." >>"${logFile}"
-	openssl genrsa -out "${caKey}" 2048
-	openssl req -x509 -new -nodes -key "${caKey}" -sha256 -days 825 -out "${caCrt}" -subj "/C=CN/CN=UnblockNeteaseMusic Root CA/O=UnblockNeteaseMusic"
-	openssl genrsa -out "${serverKey}" 2048
-	openssl req -new -sha256 -key "${serverKey}" -out "${serverCsr}" -subj "/C=CN/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=IT Dept./CN=*.music.163.com"
-	touch "${extFile}"
-	echo "authorityKeyIdentifier=keyid,issuer
-basicConstraints=CA:FALSE
-keyUsage=digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
-extendedKeyUsage=serverAuth,OCSPSigning
-subjectAltName=DNS:music.163.com,DNS:*.music.163.com" >"${extFile}"
-	openssl x509 -req -extfile "${extFile}" -days 825 -in "${serverCsr}" -CA "${caCrt}" -CAkey "${caKey}" -CAcreateserial -out "${serverCrt}"
-	rm -f "${extFile}"
-}
-start() {
-	stop >>"${logFile}" 2>&1
-	[ "${enable}" -ne "1" ] && exit 0
-	curl www.baidu.com >/dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		if [ ! -f "$serverCrt" ]; then
-			createCertificate >>"${logFile}" 2>&1
-		fi
-		if [ "${endpoint}" = "1" ]; then
-			exArgs="-e"
-		fi
-		if [ "${force_best_quality}" = "1" ]; then
-			exArgs="${exArgs} -b"
-		fi
-		if [ "${music_source}" = "default" ]; then
-			nohup UnblockNeteaseMusic -p "${http_port}" -sp "${https_port}" -o kuwo -m 0 -c "${serverCrt}" -k "${serverKey}" -l "${logFile}" -sl "${search_limit}" ${exArgs} >>"${logFile}" 2>&1 &
-		else
-			nohup UnblockNeteaseMusic -p "${http_port}" -sp "${https_port}" -o "${music_customize_source}" -m 0 -c "${serverCrt}" -k "${serverKey}" -l "${logFile}" -sl "${search_limit}" ${exArgs} >>"${logFile}" 2>&1 &
-		fi
-		set_type="start"
-		if [ "${hijack_ways}" = "use_ipset" ]; then
-			set_ipset >"/dev/null" 2>&1
-		elif [ "${hijack_ways}" = "use_hosts" ]; then
-			set_hosts >"/dev/null" 2>&1
-		fi
-	else
-		echo "$(date -R) network connection error" >>"${logFile}"
-	fi
-	sed -i '/UnblockNeteaseMusic/d' /etc/crontabs/root
-	echo "*/1 * * * * /usr/share/UnblockNeteaseMusic/log_check.sh" >>"/etc/crontabs/root"
-	echo "0 5 * * * /usr/share/UnblockNeteaseMusic/version_check.sh" >>"/etc/crontabs/root"
-	/etc/init.d/cron restart >"/dev/null" 2>&1
-}
 
-stop() {
-	killall -9 "UnblockNeteaseMusic" >"/dev/null" 2>&1
-
-	sed -i '/UnblockNeteaseMusic/d' "/etc/crontabs/root"
-	/etc/init.d/cron restart >"/dev/null" 2>&1
-
-	# rm -f "${logFile}"
-
-	set_type="stop"
-	set_ipset >"/dev/null" 2>&1
-	set_hosts >"/dev/null" 2>&1
+service_triggers() {
+	procd_add_reload_trigger "$NAME"
 }
